name: W3F Education

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
        env: 
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          git config --global user.email "w3fdeply@users.noreply.github.com"
          git config --global user.name "w3fdeploy"
          echo "machine github.com login w3fdeploy password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
          yarn && yarn build && GIT_USER=w3fdeploy PUBLISHING=true yarn deploy
